disabled_rules:
  - identifier_name
  - function_parameter_count
  - nesting
  - type_body_length
  - function_body_length
  - file_length
  - non_optional_string_data_conversion
excluded:
  - .build
