# Copyright (c) 2024 Anass Bouassaba.
#
# Use of this software is governed by the MIT License
# included in the file LICENSE in the root of this repository.

name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up SwiftLint
        run: brew install swiftlint

      - name: Lint Using SwiftLint
        run: swiftlint lint --strict .

  format:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up swift-format
        run: brew install swift-format

      - name: Lint Using swift-format
        run: swift format lint -r .