# Copyright (c) 2024 Anass Bouassaba.
#
# Use of this software is governed by the MIT License
# included in the file LICENSE in the root of this repository.

name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    container:
      image: swift:5.10-noble
    steps:
      - uses: actions/checkout@v2
      - name: Set Up swiftlint
        run: |
          sudo apt-get update && sudo apt-get install -y unzip curl
          unzip ci/swiftlint.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/swiftlint
      - name: Lint Using swiftlint
        run: swiftlint lint --strict .

  swiftformat:
    runs-on: ubuntu-latest
    container:
      image: swift:5.10-noble
    steps:
      - uses: actions/checkout@v2
      - name: Set Up swiftformat
        run: |
          sudo apt-get update && sudo apt-get install -y unzip curl
          unzip ci/swiftformat.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/swiftformat
      - name: Lint Using swiftformat
        run: swiftformat --lint .
